### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by Alekseyyy** [HACKE-RC/awesome-reversing#1]
Hey mate. Thanks for this resource; it looks like great stuff! Though I did notice that there may be a typo in the ``README.md`` file: the title "__Resource__ Engineering Resources" looks like it should be "__Reverse__ Engineering Resources." We're not having a go at you. This awesome list is... well... just awesome :fire: :star_struck:

**Comment by HACKE-RC** [comment]
Thanks! Updating it
